In [22]:
import pandas as pd

In [23]:
df1 = pd.read_csv('/content/merged_tables_0_1.csv')
df2 = pd.read_csv('/content/fifa_rankings_uefa_june_2024.csv')

In [24]:
df1.loc[df1['Team'] == 'Czech Republic', 'Team'] = 'Czechia'
df1.loc[df1['Team'] == 'Turkey', 'Team'] = 'Türkiye'

In [25]:
df1

,Team,Base Camp,Training Ground,Qualified as,Previous appearances
0,Albania,Kamen,SportCentrum Kaiserau,Group E winner,1
1,Austria,Berlin,Mommsenstadion,Group F runner-up,3
2,Belgium,Ludwigsburg,"Wasenstadion, SGV Freiberg am Neckar",Group F winner,6
3,Croatia,Neuruppin,Volksparkstadion,Group D runner-up,6
4,Czechia,Hamburg,Edmund-Plambeck-Stadion,Group E runner-up,10
5,Denmark,Freudenstadt,Hermann-Saam-Stadion,Group H winner,9
6,England,Blankenhain,Golfresort Weimarer Land,Group C winner,10
7,France,Bad Lippspringe,Home Deluxe Arena,Group B winner,10
8,Georgia,Velbert,SSVg Velbert,Play-off Path C winner,0
9,Germany,Herzogenaurach,Adidas Campus/HomeGround,Host,13
10,Hungary,Weiler-Simmerberg,"Tannenhof Resort, Sport & Spa",Group G winner,4
11,Italy,Iserlohn,Hemberg-Stadion,Group C runner-up,10
12,Netherlands,Wolfsburg,AOK Stadion,Group B runner-up,10
13,Poland,Hanover,Eilenriedestadion,Play-off Path A winner,4
14,Portugal,Harsewinkel,Hotel-Residence Klosterpforte Marienfeld / Spo...,Group J winner,8
15,Romania,Würzburg,Akon Arena,Group I winner,5
16,Scotland,Garmisch-Partenkirchen,Stadion am Gröben,Group A runner-up,3
17,Serbia,Augsburg,Rosenaustadion,Group G runner-up,5
18,Slovakia,Mainz,Bruchwegstadion,Group J runner-up,5
19,Slovenia,Wuppertal,Stadion am Zoo,Group H runner-up,1
20,Spain,Donaueschingen,Der Öschberghof,Group A winner,11
21,Switzerland,Stuttgart,Gazi-Stadion auf der Waldau,Group I runner-up,5
22,Türkiye,Barsinghausen,Sporthotel Fuchsbachtal,Group D winner,5
23,Ukraine,Wiesbaden,Stadion am Halberg,Play-off Path B winner,3

In [26]:
df2

,FIFA Ranking,Team,Total Points,Previous Points,Change in Points
0,2,France,1837.47,1840.59,-3.12
1,3,Belgium,1797.98,1795.23,2.75
2,5,England,1787.88,1794.90,-7.02
3,6,Portugal,1747.04,1748.11,-1.07
4,7,Netherlands,1746.66,1742.29,4.37
5,8,Spain,1729.92,1727.50,2.42
6,9,Croatia,1728.30,1721.07,7.23
7,10,Italy,1724.37,1724.60,-0.23
8,16,Germany,1646.78,1644.21,2.57
9,19,Switzerland,1617.24,1616.41,0.83
10,21,Denmark,1610.76,1602.72,8.04
11,24,Ukraine,1565.37,1568.86,-3.49
12,25,Austria,1560.03,1554.86,5.17
13,26,Poland,1541.49,1531.49,10.00
14,27,Hungary,1529.00,1532.20,-3.20
15,28,Sweden,1522.19,1531.68,-9.49
16,29,Wales,1521.40,1531.38,-9.98
17,32,Serbia,1514.76,1514.20,0.56
18,33,Russia,1506.58,1504.02,2.56
19,34,Czechia,1506.23,1501.47,4.76
20,39,Scotland,1497.18,1497.46,-0.28
21,42,Türkiye,1493.38,1495.94,-2.56
22,45,Slovakia,1467.77,1461.55,6.22
23,46,Norway,1466.48,1467.51,-1.03
24,47,Romania,1462.35,1468.17,-5.82
25,51,Greece,1455.95,1457.89,-1.94
26,57,Slovenia,1429.74,1427.84,1.90
27,60,Republic of Ireland,1403.84,1399.74,4.10
28,63,Finland,1393.40,1394.44,-1.04
29,66,Albania,1379.40,1375.10,4.30
30,70,Iceland,1353.48,1346.82,6.66
31,71,North Macedonia,1348.63,1354.19,-5.56
32,72,Montenegro,1345.02,1351.72,-6.70
33,73,Northern Ireland,1341.33,1341.05,0.28
34,74,Georgia,1338.91,1333.76,5.15
35,75,Bosnia and Herzegovina,1332.30,1335.60,-3.30
36,79,Israel,1312.54,1311.39,1.15
37,82,Bulgaria,1295.50,1292.59,2.91
38,85,Luxembourg,1276.73,1277.94,-1.21
39,96,Armenia,1230.79,1229.18,1.61
40,98,Belarus,1219.78,1226.54,-6.76
41,105,Kosovo,1203.16,1205.85,-2.69
42,109,Kazakhstan,1193.62,1203.64,-10.02
43,111,Azerbaijan,1179.88,1177.83,2.05
44,123,Estonia,1146.47,1141.13,5.34
45,126,Cyprus,1136.78,1141.03,-4.25
46,136,Lithuania,1100.66,1095.23,5.43
47,138,Latvia,1095.98,1095.91,0.07
48,139,Faroe Islands,1093.70,1103.43,-9.73
49,152,Moldova,1033.75,1028.85,4.90
50,162,Andorra,996.05,998.75,-2.70
51,172,Malta,970.62,973.14,-2.52
52,198,Gibraltar,836.14,832.50,3.64
53,199,Liechtenstein,835.83,832.75,3.08
54,210,San Marino,739.64,742.05,-2.41

In [30]:
df = pd.merge(df2, df1, on='Team', how='right')

In [28]:
len(pd.merge(df2, df1, on='Team', how='right'))

24

In [29]:
pd.merge(df2, df1, on='Team', how='right').isnull().sum()

FIFA Ranking            0
Team                    0
Total Points            0
Previous Points         0
Change in Points        0
Base Camp               0
Training Ground         0
Qualified as            0
Previous appearances    0
dtype: int64

In [31]:
df.to_csv('dataset_draft_v0.csv', index=False)